Test multiple generator kwargs
understanding-search/maze-dataset pull request #22
Opened 2024-01-26 23:34 UTC by aaron-sandoval

Addresses #11 
In `test_latticemaze.py`, all instances of testing over everything in `GENERATORS_MAP` have been replaced by iterating over `DEFAULT_GENERATORS`. Special exceptions for generation methods that would stochastically fail are removed.

2024-01-26 23:38 UTC, aaron-sandoval commented
Environment setup issues currently have this branch with a very different poetry.lock file. Still need to get tests to work with the original poetry.lock from the main branch before merging.

2024-01-28 02:52 UTC, mivanit requested changes
No need for the old `ORIG_poetry.lock` file, and the formatter needs to be run. Other than that, LGTM!

2024-01-28 02:52 UTC, mivanit commented on ORIG_poetry.lock
This file should just be deleted -- we updated the dependencies, so the the new `poetry.lock` is what we should care about testing with. If we ever need the old one for diagnosing an error, we can always find it in the commit history

2024-01-31 04:02 UTC, mivanit commented
looks like this might be failing due to black being bumped to version 24 (formatting checks don't respect our `pyproject.toml` deps unfortunately). maybe roll that dep update into this PR? Don't squash and merge if this PR ends up including that format run, just do a regular merge

2024-02-02 20:42 UTC, mivanit commented
looks great! Thanks for taking care of this

2024-02-02 20:42 UTC, merged